//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models.DAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class project_dotnetEntities : DbContext
    {
        public project_dotnetEntities()
            : base("name=project_dotnetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<chitietdonhang> chitietdonhangs { get; set; }
        public virtual DbSet<danhgia> danhgias { get; set; }
        public virtual DbSet<danhmuc> danhmucs { get; set; }
        public virtual DbSet<donhang> donhangs { get; set; }
        public virtual DbSet<giohang> giohangs { get; set; }
        public virtual DbSet<khachhang> khachhangs { get; set; }
        public virtual DbSet<khuyenmai> khuyenmais { get; set; }
        public virtual DbSet<phukien> phukiens { get; set; }
        public virtual DbSet<resourcetable> resourcetables { get; set; }
        public virtual DbSet<roletable> roletables { get; set; }
        public virtual DbSet<sanpham> sanphams { get; set; }
        public virtual DbSet<thongso> thongsoes { get; set; }
        public virtual DbSet<usertable> usertables { get; set; }
    }

}
